# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 24 May 2013 23:02:13 +0000
*               @ALL          1
*               @user         8
